<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSuite01_Positive</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>05ccb7b8-99b7-42ed-a3b5-e3445936f844</testSuiteGuid>
   <testCaseLink>
      <guid>772191f4-d904-415b-af37-06716f931711</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TS_01_Login/TC_01_Login using standardUser Username_Positive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c832b169-c837-454e-bd96-c5d354cd94b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2822c9d-ff31-4071-adc5-bacad1467288</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d6d9d8f-8622-45a3-9528-c3974d23a8be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TS_01_Login/TC_03_Login using problemUser Username_Positive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5098fb79-1f20-47d8-8deb-ca98abcf0d55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d696f0b-05be-4334-9e4b-22afa19c7b2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8787bf89-7d1f-4501-9f88-4c4f90a08d8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TS_01_Login/TC_04_Login using performanceGlitchUser Username_Positive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c620ae6-67d3-4a42-8c82-632c233a35c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>446f6539-c7a2-40a7-a7b8-1642b3efed94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fc2b60e-dc64-4b25-a72d-0e1a7a63fa68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TS_02_Cart/TC_05_Adding and removing cart objects using standardUser_Positive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a90d626-a782-4c0f-b2f4-0d32de392ffd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48bc4248-6d5d-4c1c-bde6-303072597298</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2eb5eda-65ec-421e-874a-1b59a23f19fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TS_03_Checkout/TC_06_Checkout using standardUser_Positive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5fb24c5-e089-409c-9986-b26c38709525</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6027b38a-9a6b-4157-8f0f-d2c2167863ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a32fd9d8-a032-42c5-b33e-9ce6ae82197e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d54e889-8ae8-4a8f-ba5c-d4a3a50be57d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5039b2bf-97be-41d7-9a9d-86d235fb809e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
